services:
  app:
    container_name: ${NAME}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_URL: https://github.com/Fydyr/discord-bot.git
        GIT_BRANCH: main
    networks:
      - lan
    restart: unless-stopped
    environment:
      DISCORD_TOKEN: "${DISCORD_TOKEN}"
      STATUS_CHANNEL_ID: "${STATUS_CHANNEL_ID}"
      LOG_WEBHOOK_URL: "${LOG_WEBHOOK_URL}"
      GEMINI_API_KEY: "${GEMINI_API_KEY}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      NODE_ENV: production

networks:
  lan:
    external: false
    name: lan_${NAME}
