import type { Language } from "./GuildSettingsService";

/**
 * Sujets tech utilisés pour le fallback Wikipedia, par langue.
 * Chaque entrée est un titre d'article valide pour l'édition Wikipedia
 * correspondante (fr., en., es., de., it.). Les sujets dont le titre est
 * identique partout (marques, Linux, GitHub…) sont repris tels quels ;
 * les titres désambiguïsés sont adaptés à chaque langue.
 */
export const TECH_TOPICS_BY_LANG: Record<Language, string[]> = {
  fr: [
    "Python_(langage)", "Java_(langage)", "JavaScript", "C_(langage)", "C%2B%2B",
    "Ruby_(langage)", "PHP", "Rust_(langage)", "Go_(langage)", "TypeScript",
    "Steve_Jobs", "Bill_Gates", "Linus_Torvalds", "Alan_Turing", "Grace_Hopper",
    "Ada_Lovelace", "Tim_Berners-Lee", "Elon_Musk", "Mark_Zuckerberg",
    "Apple", "Microsoft", "Google", "Amazon_(entreprise)", "Meta_(entreprise)",
    "Tesla_(entreprise)", "Netflix", "Nvidia", "Intel", "AMD",
    "World_Wide_Web", "Bitcoin", "Blockchain", "ChatGPT", "DeepMind",
    "Linux", "Android", "IOS", "Microsoft_Windows", "MacOS",
    "Cloud_computing", "Apprentissage_automatique", "Apprentissage_profond",
    "Réalité_virtuelle", "Réalité_augmentée", "Métavers",
    "Bug_de_l'an_2000", "Arpanet", "Ordinateur_quantique",
    "Transistor", "Microprocesseur", "Circuit_intégré", "Mémoire_vive",
    "SSD", "Processeur_graphique", "Internet_des_objets", "5G", "Fibre_optique",
    "GitHub", "Stack_Overflow", "Reddit", "Discord_(logiciel)", "Slack_(plateforme)",
    "Visual_Studio_Code", "Docker_(logiciel)", "Kubernetes",
    "Minecraft", "Fortnite", "League_of_Legends", "PlayStation", "Xbox",
    "Nintendo", "Steam_(plateforme)", "Twitch_(service)",
    "WannaCry", "Rançongiciel", "Hameçonnage", "Pare-feu_(informatique)",
    "Chiffrement", "Réseau_privé_virtuel", "Tor_(réseau)",
  ],
  en: [
    "Python_(programming_language)", "Java_(programming_language)", "JavaScript",
    "C_(programming_language)", "C%2B%2B", "Ruby_(programming_language)", "PHP",
    "Rust_(programming_language)", "Go_(programming_language)", "TypeScript",
    "Steve_Jobs", "Bill_Gates", "Linus_Torvalds", "Alan_Turing", "Grace_Hopper",
    "Ada_Lovelace", "Tim_Berners-Lee", "Elon_Musk", "Mark_Zuckerberg",
    "Apple_Inc.", "Microsoft", "Google", "Amazon_(company)", "Meta_Platforms",
    "Tesla,_Inc.", "Netflix", "Nvidia", "Intel", "AMD",
    "World_Wide_Web", "Bitcoin", "Blockchain", "ChatGPT", "Google_DeepMind",
    "Linux", "Android_(operating_system)", "IOS", "Microsoft_Windows", "MacOS",
    "Cloud_computing", "Machine_learning", "Deep_learning",
    "Virtual_reality", "Augmented_reality", "Metaverse",
    "Year_2000_problem", "ARPANET", "Quantum_computing",
    "Transistor", "Microprocessor", "Integrated_circuit", "Random-access_memory",
    "Solid-state_drive", "Graphics_processing_unit", "Internet_of_things", "5G", "Optical_fiber",
    "GitHub", "Stack_Overflow", "Reddit", "Discord", "Slack_(software)",
    "Visual_Studio_Code", "Docker_(software)", "Kubernetes",
    "Minecraft", "Fortnite", "League_of_Legends", "PlayStation", "Xbox",
    "Nintendo", "Steam_(service)", "Twitch_(service)",
    "WannaCry_ransomware_attack", "Ransomware", "Phishing", "Firewall_(computing)",
    "Encryption", "Virtual_private_network", "Tor_(network)",
  ],
  es: [
    "Python", "Java_(lenguaje_de_programación)", "JavaScript",
    "C_(lenguaje_de_programación)", "C%2B%2B", "Ruby", "PHP",
    "Rust_(lenguaje_de_programación)", "Go_(lenguaje_de_programación)", "TypeScript",
    "Steve_Jobs", "Bill_Gates", "Linus_Torvalds", "Alan_Turing", "Grace_Hopper",
    "Ada_Lovelace", "Tim_Berners-Lee", "Elon_Musk", "Mark_Zuckerberg",
    "Apple", "Microsoft", "Google", "Amazon_(empresa)", "Meta_(empresa)",
    "Tesla_(empresa)", "Netflix", "Nvidia", "Intel", "AMD",
    "World_Wide_Web", "Bitcoin", "Cadena_de_bloques", "ChatGPT", "Google_DeepMind",
    "Linux", "Android", "IOS", "Microsoft_Windows", "MacOS",
    "Computación_en_la_nube", "Aprendizaje_automático", "Aprendizaje_profundo",
    "Realidad_virtual", "Realidad_aumentada", "Metaverso",
    "Problema_del_año_2000", "ARPANET", "Computación_cuántica",
    "Transistor", "Microprocesador", "Circuito_integrado", "Memoria_de_acceso_aleatorio",
    "Unidad_de_estado_sólido", "Unidad_de_procesamiento_gráfico", "Internet_de_las_cosas", "5G", "Fibra_óptica",
    "GitHub", "Stack_Overflow", "Reddit", "Discord", "Slack_(software)",
    "Visual_Studio_Code", "Docker_(software)", "Kubernetes",
    "Minecraft", "Fortnite", "League_of_Legends", "PlayStation", "Xbox",
    "Nintendo", "Steam_(plataforma_de_distribución_digital)", "Twitch",
    "WannaCry", "Ransomware", "Phishing", "Cortafuegos_(informática)",
    "Cifrado_(criptografía)", "Red_privada_virtual", "Tor_(red_de_anonimato)",
  ],
  de: [
    "Python_(Programmiersprache)", "Java_(Programmiersprache)", "JavaScript",
    "C_(Programmiersprache)", "C%2B%2B", "Ruby_(Programmiersprache)", "PHP",
    "Rust_(Programmiersprache)", "Go_(Programmiersprache)", "TypeScript",
    "Steve_Jobs", "Bill_Gates", "Linus_Torvalds", "Alan_Turing", "Grace_Hopper",
    "Ada_Lovelace", "Tim_Berners-Lee", "Elon_Musk", "Mark_Zuckerberg",
    "Apple", "Microsoft", "Google", "Amazon_(Unternehmen)", "Meta_Platforms",
    "Tesla,_Inc.", "Netflix", "Nvidia", "Intel", "AMD",
    "World_Wide_Web", "Bitcoin", "Blockchain", "ChatGPT", "Google_DeepMind",
    "Linux_(Kernel)", "Android_(Betriebssystem)", "IOS_(Betriebssystem)", "Microsoft_Windows", "MacOS",
    "Cloud_Computing", "Maschinelles_Lernen", "Deep_Learning",
    "Virtuelle_Realität", "Erweiterte_Realität", "Metaverse",
    "Jahr-2000-Problem", "Arpanet", "Quantencomputer",
    "Transistor", "Mikroprozessor", "Integrierter_Schaltkreis", "Random-Access_Memory",
    "Solid-State-Drive", "Grafikprozessor", "Internet_der_Dinge", "5G", "Glasfaser",
    "GitHub", "Stack_Overflow", "Reddit", "Discord", "Slack_(Software)",
    "Visual_Studio_Code", "Docker_(Software)", "Kubernetes",
    "Minecraft", "Fortnite", "League_of_Legends", "PlayStation", "Xbox",
    "Nintendo", "Steam_(Software)", "Twitch",
    "WannaCry", "Ransomware", "Phishing", "Firewall",
    "Verschlüsselung", "Virtual_Private_Network", "Tor_(Netzwerk)",
  ],
  it: [
    "Python", "Java_(linguaggio_di_programmazione)", "JavaScript",
    "C_(linguaggio)", "C%2B%2B", "Ruby_(linguaggio_di_programmazione)", "PHP",
    "Rust_(linguaggio_di_programmazione)", "Go_(linguaggio_di_programmazione)", "TypeScript",
    "Steve_Jobs", "Bill_Gates", "Linus_Torvalds", "Alan_Turing", "Grace_Hopper",
    "Ada_Lovelace", "Tim_Berners-Lee", "Elon_Musk", "Mark_Zuckerberg",
    "Apple", "Microsoft", "Google", "Amazon_(azienda)", "Meta_Platforms",
    "Tesla_(azienda)", "Netflix", "Nvidia", "Intel", "AMD",
    "World_Wide_Web", "Bitcoin", "Blockchain", "ChatGPT", "Google_DeepMind",
    "Linux", "Android", "IOS", "Microsoft_Windows", "MacOS",
    "Cloud_computing", "Apprendimento_automatico", "Apprendimento_profondo",
    "Realtà_virtuale", "Realtà_aumentata", "Metaverso",
    "Millennium_bug", "ARPANET", "Computer_quantistico",
    "Transistor", "Microprocessore", "Circuito_integrato", "Random-access_memory",
    "Unità_a_stato_solido", "Unità_di_elaborazione_grafica", "Internet_delle_cose", "5G", "Fibra_ottica",
    "GitHub", "Stack_Overflow", "Reddit", "Discord_(software)", "Slack_(software)",
    "Visual_Studio_Code", "Docker_(software)", "Kubernetes",
    "Minecraft", "Fortnite", "League_of_Legends", "PlayStation", "Xbox",
    "Nintendo", "Steam_(piattaforma)", "Twitch_(piattaforma)",
    "WannaCry", "Ransomware", "Phishing", "Firewall",
    "Crittografia", "Rete_privata_virtuale", "Tor_(software)",
  ],
};
